/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  napiSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'introduction/getting-started',
        'introduction/native-module',
        'introduction/history',
        'introduction/release',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: ['concepts/exports', 'concepts/values'],
    },
    {
      type: 'category',
      label: 'V1 Docs',
      items: [
        {
          type: 'category',
          label: 'Concepts',
          items: [
            {
              type: 'autogenerated',
              dirName: 'compat-mode/concepts',
            },
          ],
        },
        {
          type: 'category',
          label: 'Recipes',
          items: [
            {
              type: 'autogenerated',
              dirName: 'compat-mode/recipes',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ecosystem',
        },
      ],
    },
    {
      type: 'category',
      label: 'Changelog',
      items: [
        {
          type: 'autogenerated',
          dirName: 'changelog',
        },
      ],
    },
    {
      type: 'category',
      label: 'More',
      items: ['faq', 'neon'],
    },
  ],
}
